/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author gamer
 */
public class Achat extends javax.swing.JFrame {

    public void Run() {
        initComponents();
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        getRootPane().setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(208, 208, 208)));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fermer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Produit_Fenetre = new javax.swing.JPanel();
        Produit_FenetreL = new javax.swing.JLabel();
        Achat_Fenetre = new javax.swing.JPanel();
        Achat_FenetreL = new javax.swing.JLabel();
        Vente_Fenetre = new javax.swing.JPanel();
        Vente_FenetreL = new javax.swing.JLabel();
        Fournisseur_Fenetre = new javax.swing.JPanel();
        Fournisseur_FenetreL = new javax.swing.JLabel();
        Client_Fenetre = new javax.swing.JPanel();
        Client_FenetreL = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Donner_Achat = new javax.swing.JTable();
        ajouter = new javax.swing.JPanel();
        Ajouter_achat = new javax.swing.JLabel();
        Modifer = new javax.swing.JPanel();
        Modifier_Achat = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        Suprrimer_Achat = new javax.swing.JLabel();
        Rechercher = new javax.swing.JLabel();
        Recherche = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 60));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        fermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fermerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fermerMouseExited(evt);
            }
        });
        jPanel2.add(fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_hover.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Achat");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 190, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 820, 50));

        jPanel3.setBackground(new java.awt.Color(193, 57, 43));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Produit_Fenetre.setBackground(new java.awt.Color(193, 57, 43));
        Produit_Fenetre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Produit_FenetreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Produit_FenetreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Produit_FenetreMouseExited(evt);
            }
        });
        Produit_Fenetre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Produit_FenetreL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Produit_FenetreL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min/box_hover.png"))); // NOI18N
        Produit_Fenetre.add(Produit_FenetreL, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        jPanel3.add(Produit_Fenetre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 39, 39));

        Achat_Fenetre.setBackground(new java.awt.Color(193, 57, 43));
        Achat_Fenetre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Achat_FenetreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Achat_FenetreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Achat_FenetreMouseExited(evt);
            }
        });
        Achat_Fenetre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Achat_FenetreL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Achat_FenetreL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min/panier_hover.png"))); // NOI18N
        Achat_Fenetre.add(Achat_FenetreL, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        jPanel3.add(Achat_Fenetre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 39, 39));

        Vente_Fenetre.setBackground(new java.awt.Color(193, 57, 43));
        Vente_Fenetre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Vente_FenetreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Vente_FenetreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Vente_FenetreMouseExited(evt);
            }
        });
        Vente_Fenetre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Vente_FenetreL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Vente_FenetreL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min/mainPanier_hover.png"))); // NOI18N
        Vente_Fenetre.add(Vente_FenetreL, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        jPanel3.add(Vente_Fenetre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 39, 39));

        Fournisseur_Fenetre.setBackground(new java.awt.Color(193, 57, 43));
        Fournisseur_Fenetre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Fournisseur_FenetreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Fournisseur_FenetreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Fournisseur_FenetreMouseExited(evt);
            }
        });
        Fournisseur_Fenetre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fournisseur_FenetreL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fournisseur_FenetreL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min/man_hover.png"))); // NOI18N
        Fournisseur_Fenetre.add(Fournisseur_FenetreL, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        jPanel3.add(Fournisseur_Fenetre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 39, 39));

        Client_Fenetre.setBackground(new java.awt.Color(193, 57, 43));
        Client_Fenetre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Client_FenetreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Client_FenetreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Client_FenetreMouseExited(evt);
            }
        });
        Client_Fenetre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Client_FenetreL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Client_FenetreL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min/profile_hover.png"))); // NOI18N
        Client_Fenetre.add(Client_FenetreL, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        jPanel3.add(Client_Fenetre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 39, 39));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 490));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Donner_Achat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Donner_Achat.setForeground(new java.awt.Color(51, 51, 51));
        Donner_Achat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Date", "Designation", "Qt", "Prix_H.T", "Fournisseur", "Versement"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Donner_Achat.setGridColor(new java.awt.Color(193, 57, 43));
        Donner_Achat.setPreferredSize(new java.awt.Dimension(375, 16));
        Donner_Achat.setRowSelectionAllowed(false);
        Donner_Achat.setSelectionBackground(new java.awt.Color(232, 76, 61));
        jScrollPane1.setViewportView(Donner_Achat);
        if (Donner_Achat.getColumnModel().getColumnCount() > 0) {
            Donner_Achat.getColumnModel().getColumn(0).setResizable(false);
            Donner_Achat.getColumnModel().getColumn(1).setResizable(false);
            Donner_Achat.getColumnModel().getColumn(2).setResizable(false);
            Donner_Achat.getColumnModel().getColumn(3).setResizable(false);
            Donner_Achat.getColumnModel().getColumn(4).setResizable(false);
            Donner_Achat.getColumnModel().getColumn(5).setResizable(false);
            Donner_Achat.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 820, 360));

        ajouter.setBackground(new java.awt.Color(255, 255, 255));
        ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajouterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajouterMouseExited(evt);
            }
        });
        ajouter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ajouter_achat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_achat_hover.png"))); // NOI18N
        ajouter.add(Ajouter_achat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel9.add(ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        Modifer.setBackground(new java.awt.Color(255, 255, 255));
        Modifer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModiferMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ModiferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ModiferMouseExited(evt);
            }
        });
        Modifer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Modifier_Achat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edi_achat_hover.png"))); // NOI18N
        Modifer.add(Modifier_Achat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel9.add(Modifer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 50));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel12MouseExited(evt);
            }
        });
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Suprrimer_Achat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/del_achat_hover.png"))); // NOI18N
        jPanel12.add(Suprrimer_Achat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 50));

        Rechercher.setBackground(new java.awt.Color(232, 76, 61));
        Rechercher.setForeground(new java.awt.Color(255, 255, 255));
        Rechercher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Rechercher.setText("Recherche");
        Rechercher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(193, 57, 43)));
        Rechercher.setOpaque(true);
        Rechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RechercherMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RechercherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RechercherMouseExited(evt);
            }
        });
        jPanel9.add(Rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 100, 30));

        Recherche.setBackground(new java.awt.Color(236, 240, 241));
        Recherche.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Recherche.setForeground(new java.awt.Color(51, 51, 51));
        Recherche.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Recherche.setText("Recherche");
        Recherche.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel9.add(Recherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 270, 30));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 820, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseClicked
        this.dispose();
    }//GEN-LAST:event_fermerMouseClicked

    private void fermerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseEntered
        fermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close_hover.png")));
    }//GEN-LAST:event_fermerMouseEntered

    private void fermerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseExited
        fermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png")));
    }//GEN-LAST:event_fermerMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        home h = new home();
        this.dispose();
        h.Run();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png")));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_hover.png")));
    }//GEN-LAST:event_jLabel2MouseExited

    private void Produit_FenetreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Produit_FenetreMouseEntered
        MouseEntred(Produit_Fenetre, Produit_FenetreL, "box");
    }//GEN-LAST:event_Produit_FenetreMouseEntered

    private void Produit_FenetreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Produit_FenetreMouseExited
        MouseOut(Produit_Fenetre, Produit_FenetreL, "box");
    }//GEN-LAST:event_Produit_FenetreMouseExited

    private void Achat_FenetreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Achat_FenetreMouseEntered
        MouseEntred(Achat_Fenetre, Achat_FenetreL, "panier");
    }//GEN-LAST:event_Achat_FenetreMouseEntered

    private void Achat_FenetreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Achat_FenetreMouseExited
        MouseOut(Achat_Fenetre, Achat_FenetreL, "panier");
    }//GEN-LAST:event_Achat_FenetreMouseExited

    private void Vente_FenetreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Vente_FenetreMouseEntered
        MouseEntred(Vente_Fenetre, Vente_FenetreL, "mainPanier");
    }//GEN-LAST:event_Vente_FenetreMouseEntered

    private void Vente_FenetreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Vente_FenetreMouseExited
        MouseOut(Vente_Fenetre, Vente_FenetreL, "mainPanier");
    }//GEN-LAST:event_Vente_FenetreMouseExited

    private void Fournisseur_FenetreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fournisseur_FenetreMouseEntered
        MouseEntred(Fournisseur_Fenetre, Fournisseur_FenetreL, "man");
    }//GEN-LAST:event_Fournisseur_FenetreMouseEntered

    private void Fournisseur_FenetreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fournisseur_FenetreMouseExited
        MouseOut(Fournisseur_Fenetre, Fournisseur_FenetreL, "man");
    }//GEN-LAST:event_Fournisseur_FenetreMouseExited

    private void Client_FenetreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Client_FenetreMouseEntered
        MouseEntred(Client_Fenetre, Client_FenetreL, "profile");
    }//GEN-LAST:event_Client_FenetreMouseEntered

    private void Client_FenetreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Client_FenetreMouseExited
        MouseOut(Client_Fenetre, Client_FenetreL, "profile");
    }//GEN-LAST:event_Client_FenetreMouseExited

    private void Produit_FenetreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Produit_FenetreMouseClicked
          ProduitList produitlist = new ProduitList();
        this.dispose();
        produitlist.Run();
    }//GEN-LAST:event_Produit_FenetreMouseClicked

    private void Achat_FenetreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Achat_FenetreMouseClicked
        Achat Achat = new Achat();
        this.dispose();
        Achat.Run();
    }//GEN-LAST:event_Achat_FenetreMouseClicked

    private void Vente_FenetreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Vente_FenetreMouseClicked
        Vente Vente = new Vente();
        this.dispose();
        Vente.Run();
    }//GEN-LAST:event_Vente_FenetreMouseClicked

    private void Fournisseur_FenetreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fournisseur_FenetreMouseClicked
        Fournisseur Fournisseur = new Fournisseur();
        this.dispose();
        Fournisseur.Run();
    }//GEN-LAST:event_Fournisseur_FenetreMouseClicked

    private void Client_FenetreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Client_FenetreMouseClicked
         Client Client = new Client();
        this.dispose();
        Client.Run();
    }//GEN-LAST:event_Client_FenetreMouseClicked

    private void ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseClicked
        AddAchat addachat = new AddAchat();
        this.dispose();
        addachat.Run(0);

    }//GEN-LAST:event_ajouterMouseClicked

    private void ajouterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseEntered
        Ajouter_achat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_achat.png")));
    }//GEN-LAST:event_ajouterMouseEntered

    private void ajouterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseExited
        Ajouter_achat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_achat_hover.png")));
    }//GEN-LAST:event_ajouterMouseExited

    private void ModiferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModiferMouseClicked
        AjouterProduit addProduit = new AjouterProduit();
        this.dispose();
        addProduit.Run(true);
    }//GEN-LAST:event_ModiferMouseClicked

    private void ModiferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModiferMouseEntered
        Modifier_Achat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edi_achat.png")));
    }//GEN-LAST:event_ModiferMouseEntered

    private void ModiferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModiferMouseExited
        Modifier_Achat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edi_achat_hover.png")));
    }//GEN-LAST:event_ModiferMouseExited

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel12MouseClicked

    private void jPanel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseEntered
        Suprrimer_Achat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/del_achat.png")));
    }//GEN-LAST:event_jPanel12MouseEntered

    private void jPanel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseExited
        Suprrimer_Achat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/del_achat_hover.png")));
    }//GEN-LAST:event_jPanel12MouseExited

    private void RechercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherMouseClicked

    }//GEN-LAST:event_RechercherMouseClicked

    private void RechercherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherMouseEntered
        Rechercher.setBackground(new java.awt.Color(255, 255, 255));
        Rechercher.setForeground(new java.awt.Color(232, 76, 61));
    }//GEN-LAST:event_RechercherMouseEntered

    private void RechercherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherMouseExited
        Rechercher.setBackground(new java.awt.Color(232, 76, 61));
        Rechercher.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_RechercherMouseExited

    /**
     * @param args the command line arguments
     */
         private void MouseEntred(javax.swing.JPanel panel,javax.swing.JLabel label, String iconName){
         panel.setBackground(new Color(243, 113, 91));   
         label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min/"+iconName+".png")));
    }
    private void MouseOut(javax.swing.JPanel panel,javax.swing.JLabel label, String iconName){
        panel.setBackground(new Color(193, 57, 43));
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min/"+iconName+"_hover.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Achat_Fenetre;
    private javax.swing.JLabel Achat_FenetreL;
    private javax.swing.JLabel Ajouter_achat;
    private javax.swing.JPanel Client_Fenetre;
    private javax.swing.JLabel Client_FenetreL;
    private javax.swing.JTable Donner_Achat;
    private javax.swing.JPanel Fournisseur_Fenetre;
    private javax.swing.JLabel Fournisseur_FenetreL;
    private javax.swing.JPanel Modifer;
    private javax.swing.JLabel Modifier_Achat;
    private javax.swing.JPanel Produit_Fenetre;
    private javax.swing.JLabel Produit_FenetreL;
    private javax.swing.JTextField Recherche;
    private javax.swing.JLabel Rechercher;
    private javax.swing.JLabel Suprrimer_Achat;
    private javax.swing.JPanel Vente_Fenetre;
    private javax.swing.JLabel Vente_FenetreL;
    private javax.swing.JPanel ajouter;
    private javax.swing.JLabel fermer;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
