/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author gamer
 */
public class AjouterVente extends javax.swing.JFrame {
private int TYPE ;
    public void Run(int TYPE) {
    this.TYPE=TYPE;
        initComponents();
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
           if (TYPE==1){
                Titre.setText("Modifier une Vente");
                Ajouter.setText("Modifier");
           }
           
        getRootPane().setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(208, 208, 208)));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Clients = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Dates = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Ajouter = new javax.swing.JLabel();
        Annuler = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        donner_vente = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Closes = new javax.swing.JLabel();
        returns = new javax.swing.JLabel();
        Titre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(232, 76, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Clients.setBackground(new java.awt.Color(236, 240, 241));
        Clients.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Clients.setForeground(new java.awt.Color(51, 51, 51));
        Clients.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel2.add(Clients, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 270, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(193, 57, 43));
        jLabel3.setText("Client:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(193, 57, 43));
        jLabel9.setText("Designation et Quantité:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));

        Dates.setBackground(new java.awt.Color(236, 240, 241));
        Dates.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Dates.setForeground(new java.awt.Color(51, 51, 51));
        Dates.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel2.add(Dates, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 270, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(193, 57, 43));
        jLabel8.setText("Date :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, 30));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addVentes.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 110, 100));

        Ajouter.setBackground(new java.awt.Color(232, 76, 61));
        Ajouter.setForeground(new java.awt.Color(255, 255, 255));
        Ajouter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ajouter.setText("Ajouter");
        Ajouter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(193, 57, 43)));
        Ajouter.setOpaque(true);
        Ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AjouterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AjouterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AjouterMouseExited(evt);
            }
        });
        jPanel2.add(Ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 100, 30));

        Annuler.setBackground(new java.awt.Color(255, 255, 255));
        Annuler.setForeground(new java.awt.Color(51, 51, 51));
        Annuler.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Annuler.setText("Annuler");
        Annuler.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Annuler.setOpaque(true);
        Annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnnulerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AnnulerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AnnulerMouseExited(evt);
            }
        });
        jPanel2.add(Annuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 100, 30));

        donner_vente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        donner_vente.setForeground(new java.awt.Color(51, 51, 51));
        donner_vente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Designation", "Qt", "Prix_H.T"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        donner_vente.setGridColor(new java.awt.Color(193, 57, 43));
        donner_vente.setPreferredSize(new java.awt.Dimension(375, 16));
        donner_vente.setRowSelectionAllowed(false);
        donner_vente.setSelectionBackground(new java.awt.Color(232, 76, 61));
        jScrollPane1.setViewportView(donner_vente);
        if (donner_vente.getColumnModel().getColumnCount() > 0) {
            donner_vente.getColumnModel().getColumn(0).setResizable(false);
            donner_vente.getColumnModel().getColumn(1).setResizable(false);
            donner_vente.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 580, 190));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 620, 490));

        jPanel1.setBackground(new java.awt.Color(232, 76, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Closes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        Closes.setText("jLabel5");
        Closes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClosesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClosesMouseExited(evt);
            }
        });
        jPanel1.add(Closes, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 50, -1));

        returns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        returns.setText("jLabel6");
        returns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnsMouseExited(evt);
            }
        });
        jPanel1.add(returns, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        Titre.setBackground(new java.awt.Color(255, 255, 255));
        Titre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Titre.setForeground(new java.awt.Color(255, 255, 255));
        Titre.setText("Ajouter Une Vente");
        jPanel1.add(Titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjouterMouseClicked

    }//GEN-LAST:event_AjouterMouseClicked

    private void AjouterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjouterMouseEntered
        Ajouter.setBackground(new java.awt.Color(255, 255, 255));
        Ajouter.setForeground(new java.awt.Color(232, 76, 61));
    }//GEN-LAST:event_AjouterMouseEntered

    private void AjouterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjouterMouseExited
        Ajouter.setBackground(new java.awt.Color(232, 76, 61));
        Ajouter.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_AjouterMouseExited

    private void AnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnulerMouseClicked
  Vente vente = new Vente();
        this.dispose();
       vente.Run();
    }//GEN-LAST:event_AnnulerMouseClicked

    private void AnnulerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnulerMouseEntered
        Annuler.setForeground(new java.awt.Color(193, 57, 43));
        Annuler.setBackground(new java.awt.Color(236, 240, 241));
    }//GEN-LAST:event_AnnulerMouseEntered

    private void AnnulerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnulerMouseExited
        Annuler.setForeground(new java.awt.Color(51, 51, 51));
        Annuler.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_AnnulerMouseExited

    private void ClosesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosesMouseExited
         Closes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
    }//GEN-LAST:event_ClosesMouseExited

    private void ClosesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosesMouseEntered
      Closes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close_hover.png"))); // NOI18N
    }//GEN-LAST:event_ClosesMouseEntered

    private void ClosesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosesMouseClicked
      
        this.dispose();
      

    }//GEN-LAST:event_ClosesMouseClicked

    private void returnsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnsMouseExited
         returns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
    }//GEN-LAST:event_returnsMouseExited

    private void returnsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnsMouseEntered
        returns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back_hover.png"))); // NOI18N
    }//GEN-LAST:event_returnsMouseEntered

    private void returnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnsMouseClicked
          Vente vente = new Vente();
        this.dispose();
       vente.Run();
    }//GEN-LAST:event_returnsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ajouter;
    private javax.swing.JLabel Annuler;
    private javax.swing.JTextField Clients;
    private javax.swing.JLabel Closes;
    private javax.swing.JTextField Dates;
    private javax.swing.JLabel Titre;
    private javax.swing.JTable donner_vente;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel returns;
    // End of variables declaration//GEN-END:variables
}
