/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author gamer
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    public void Run() {
        initComponents();
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        getRootPane().setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(208, 208, 208)));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fermer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Produit_Fenetre = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Achat_Fenetre = new javax.swing.JPanel();
        Achat_FenetreL = new javax.swing.JLabel();
        Vente_Fenetre = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Fournisseur_Fenetre = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Client_Fenetre = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Donner_Client = new javax.swing.JTable();
        Ajouter_events = new javax.swing.JPanel();
        Ajouter_Client = new javax.swing.JLabel();
        Modifie_events = new javax.swing.JPanel();
        Modifier_Client = new javax.swing.JLabel();
        suprimer_events = new javax.swing.JPanel();
        Suprrimer_Client = new javax.swing.JLabel();
        Rechercher = new javax.swing.JLabel();
        Recherche = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 60));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(232, 76, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        fermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fermerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fermerMouseExited(evt);
            }
        });
        jPanel1.add(fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_hover.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Client");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 190, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 820, 50));

        jPanel9.setBackground(new java.awt.Color(193, 57, 43));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Produit_Fenetre.setBackground(new java.awt.Color(193, 57, 43));
        Produit_Fenetre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Produit_FenetreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Produit_FenetreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Produit_FenetreMouseExited(evt);
            }
        });
        Produit_Fenetre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min/box_hover.png"))); // NOI18N
        Produit_Fenetre.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        jPanel9.add(Produit_Fenetre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 39, 39));

        Achat_Fenetre.setBackground(new java.awt.Color(193, 57, 43));
        Achat_Fenetre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Achat_FenetreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Achat_FenetreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Achat_FenetreMouseExited(evt);
            }
        });
        Achat_Fenetre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Achat_FenetreL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Achat_FenetreL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min/panier_hover.png"))); // NOI18N
        Achat_Fenetre.add(Achat_FenetreL, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        jPanel9.add(Achat_Fenetre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 39, 39));

        Vente_Fenetre.setBackground(new java.awt.Color(193, 57, 43));
        Vente_Fenetre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Vente_FenetreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Vente_FenetreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Vente_FenetreMouseExited(evt);
            }
        });
        Vente_Fenetre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min/mainPanier_hover.png"))); // NOI18N
        Vente_Fenetre.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        jPanel9.add(Vente_Fenetre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 39, 39));

        Fournisseur_Fenetre.setBackground(new java.awt.Color(193, 57, 43));
        Fournisseur_Fenetre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Fournisseur_FenetreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Fournisseur_FenetreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Fournisseur_FenetreMouseExited(evt);
            }
        });
        Fournisseur_Fenetre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min/man_hover.png"))); // NOI18N
        Fournisseur_Fenetre.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        jPanel9.add(Fournisseur_Fenetre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 39, 39));

        Client_Fenetre.setBackground(new java.awt.Color(193, 57, 43));
        Client_Fenetre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Client_FenetreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Client_FenetreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Client_FenetreMouseExited(evt);
            }
        });
        Client_Fenetre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min/profile_hover.png"))); // NOI18N
        Client_Fenetre.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        jPanel9.add(Client_Fenetre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 39, 39));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 490));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Donner_Client.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Donner_Client.setForeground(new java.awt.Color(51, 51, 51));
        Donner_Client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Prénom", "Address", "Num Téléphone", "Crédit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Donner_Client.setGridColor(new java.awt.Color(193, 57, 43));
        Donner_Client.setPreferredSize(new java.awt.Dimension(375, 16));
        Donner_Client.setRowSelectionAllowed(false);
        Donner_Client.setSelectionBackground(new java.awt.Color(232, 76, 61));
        jScrollPane1.setViewportView(Donner_Client);
        if (Donner_Client.getColumnModel().getColumnCount() > 0) {
            Donner_Client.getColumnModel().getColumn(0).setResizable(false);
            Donner_Client.getColumnModel().getColumn(1).setResizable(false);
            Donner_Client.getColumnModel().getColumn(2).setResizable(false);
            Donner_Client.getColumnModel().getColumn(3).setResizable(false);
            Donner_Client.getColumnModel().getColumn(4).setResizable(false);
            Donner_Client.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 820, 360));

        Ajouter_events.setBackground(new java.awt.Color(255, 255, 255));
        Ajouter_events.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ajouter_eventsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ajouter_eventsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ajouter_eventsMouseExited(evt);
            }
        });
        Ajouter_events.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ajouter_Client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_client_hover.png"))); // NOI18N
        Ajouter_events.add(Ajouter_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(Ajouter_events, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        Modifie_events.setBackground(new java.awt.Color(255, 255, 255));
        Modifie_events.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Modifie_eventsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Modifie_eventsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Modifie_eventsMouseExited(evt);
            }
        });
        Modifie_events.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Modifier_Client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edi_client_hover.png"))); // NOI18N
        Modifie_events.add(Modifier_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(Modifie_events, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 50));

        suprimer_events.setBackground(new java.awt.Color(255, 255, 255));
        suprimer_events.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suprimer_eventsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suprimer_eventsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suprimer_eventsMouseExited(evt);
            }
        });
        suprimer_events.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Suprrimer_Client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/del_client_hover.png"))); // NOI18N
        suprimer_events.add(Suprrimer_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(suprimer_events, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 50));

        Rechercher.setBackground(new java.awt.Color(232, 76, 61));
        Rechercher.setForeground(new java.awt.Color(255, 255, 255));
        Rechercher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Rechercher.setText("Recherche");
        Rechercher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(193, 57, 43)));
        Rechercher.setOpaque(true);
        Rechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RechercherMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RechercherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RechercherMouseExited(evt);
            }
        });
        jPanel2.add(Rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 100, 30));

        Recherche.setBackground(new java.awt.Color(236, 240, 241));
        Recherche.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Recherche.setForeground(new java.awt.Color(51, 51, 51));
        Recherche.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Recherche.setText("Recherche");
        Recherche.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel2.add(Recherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 270, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 820, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseClicked
        this.dispose();
    }//GEN-LAST:event_fermerMouseClicked

    private void fermerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseEntered
        fermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close_hover.png")));
    }//GEN-LAST:event_fermerMouseEntered

    private void fermerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseExited
        fermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png")));
    }//GEN-LAST:event_fermerMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        home h = new home();
        this.dispose();
        h.Run();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png")));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_hover.png")));
    }//GEN-LAST:event_jLabel2MouseExited

    private void Produit_FenetreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Produit_FenetreMouseClicked
        ProduitList produitlist = new ProduitList();
        this.dispose();
        produitlist.Run();
    }//GEN-LAST:event_Produit_FenetreMouseClicked

    private void Produit_FenetreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Produit_FenetreMouseEntered
        MouseEntred(Produit_Fenetre, jLabel3, "box");
    }//GEN-LAST:event_Produit_FenetreMouseEntered

    private void Produit_FenetreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Produit_FenetreMouseExited
        MouseOut(Produit_Fenetre, jLabel3, "box");
    }//GEN-LAST:event_Produit_FenetreMouseExited

    private void Achat_FenetreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Achat_FenetreMouseClicked
        Achat Achat = new Achat();
        this.dispose();
        Achat.Run();
    }//GEN-LAST:event_Achat_FenetreMouseClicked

    private void Achat_FenetreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Achat_FenetreMouseEntered
        MouseEntred(Achat_Fenetre, Achat_FenetreL, "panier");
    }//GEN-LAST:event_Achat_FenetreMouseEntered

    private void Achat_FenetreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Achat_FenetreMouseExited
        MouseOut(Achat_Fenetre, Achat_FenetreL, "panier");
    }//GEN-LAST:event_Achat_FenetreMouseExited

    private void Vente_FenetreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Vente_FenetreMouseClicked
        Vente Vente = new Vente();
        this.dispose();
        Vente.Run();
    }//GEN-LAST:event_Vente_FenetreMouseClicked

    private void Vente_FenetreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Vente_FenetreMouseEntered
        MouseEntred(Vente_Fenetre, jLabel5, "mainPanier");
    }//GEN-LAST:event_Vente_FenetreMouseEntered

    private void Vente_FenetreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Vente_FenetreMouseExited
        MouseOut(Vente_Fenetre, jLabel5, "mainPanier");
    }//GEN-LAST:event_Vente_FenetreMouseExited

    private void Fournisseur_FenetreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fournisseur_FenetreMouseClicked
        Fournisseur Fournisseur = new Fournisseur();
        this.dispose();
        Fournisseur.Run();
    }//GEN-LAST:event_Fournisseur_FenetreMouseClicked

    private void Client_FenetreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Client_FenetreMouseClicked
        Client Client = new Client();
        this.dispose();
        Client.Run();
    }//GEN-LAST:event_Client_FenetreMouseClicked

    private void Ajouter_eventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ajouter_eventsMouseClicked
        AjouterCli_Four AddClient = new AjouterCli_Four();
        this.dispose();
        AddClient.Run(0);

    }//GEN-LAST:event_Ajouter_eventsMouseClicked

    private void Ajouter_eventsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ajouter_eventsMouseEntered
        Ajouter_Client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_client.png")));
    }//GEN-LAST:event_Ajouter_eventsMouseEntered

    private void Ajouter_eventsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ajouter_eventsMouseExited
        Ajouter_Client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_client_hover.png")));
    }//GEN-LAST:event_Ajouter_eventsMouseExited

    private void Modifie_eventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Modifie_eventsMouseClicked
        AjouterCli_Four modClient = new AjouterCli_Four();
        this.dispose();
        modClient.Run(1);
    }//GEN-LAST:event_Modifie_eventsMouseClicked

    private void Modifie_eventsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Modifie_eventsMouseEntered
        Modifier_Client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edi_client.png")));
    }//GEN-LAST:event_Modifie_eventsMouseEntered

    private void Modifie_eventsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Modifie_eventsMouseExited
        Modifier_Client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edi_client_hover.png")));
    }//GEN-LAST:event_Modifie_eventsMouseExited

    private void suprimer_eventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suprimer_eventsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_suprimer_eventsMouseClicked

    private void suprimer_eventsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suprimer_eventsMouseEntered
        Suprrimer_Client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/del_client.png")));
    }//GEN-LAST:event_suprimer_eventsMouseEntered

    private void suprimer_eventsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suprimer_eventsMouseExited
        Suprrimer_Client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/del_client_hover.png")));
    }//GEN-LAST:event_suprimer_eventsMouseExited

    private void RechercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherMouseClicked

    }//GEN-LAST:event_RechercherMouseClicked

    private void RechercherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherMouseEntered
        Rechercher.setBackground(new java.awt.Color(255, 255, 255));
        Rechercher.setForeground(new java.awt.Color(232, 76, 61));
    }//GEN-LAST:event_RechercherMouseEntered

    private void RechercherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherMouseExited
        Rechercher.setBackground(new java.awt.Color(232, 76, 61));
        Rechercher.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_RechercherMouseExited

    private void Client_FenetreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Client_FenetreMouseExited
        MouseOut(Client_Fenetre, jLabel7, "profile");
    }//GEN-LAST:event_Client_FenetreMouseExited

    private void Client_FenetreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Client_FenetreMouseEntered
        MouseEntred(Client_Fenetre, jLabel7, "profile");
    }//GEN-LAST:event_Client_FenetreMouseEntered

    private void Fournisseur_FenetreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fournisseur_FenetreMouseEntered
        MouseEntred(Fournisseur_Fenetre, jLabel6, "man");
    }//GEN-LAST:event_Fournisseur_FenetreMouseEntered

    private void Fournisseur_FenetreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fournisseur_FenetreMouseExited
        MouseOut(Fournisseur_Fenetre, jLabel6, "man");
    }//GEN-LAST:event_Fournisseur_FenetreMouseExited
          private void MouseEntred(javax.swing.JPanel panel,javax.swing.JLabel label, String iconName){
         panel.setBackground(new Color(243, 113, 91));   
         label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min/"+iconName+".png")));
    }
    private void MouseOut(javax.swing.JPanel panel,javax.swing.JLabel label, String iconName){
        panel.setBackground(new Color(193, 57, 43));
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min/"+iconName+"_hover.png")));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Achat_Fenetre;
    private javax.swing.JLabel Achat_FenetreL;
    private javax.swing.JLabel Ajouter_Client;
    private javax.swing.JPanel Ajouter_events;
    private javax.swing.JPanel Client_Fenetre;
    private javax.swing.JTable Donner_Client;
    private javax.swing.JPanel Fournisseur_Fenetre;
    private javax.swing.JPanel Modifie_events;
    private javax.swing.JLabel Modifier_Client;
    private javax.swing.JPanel Produit_Fenetre;
    private javax.swing.JTextField Recherche;
    private javax.swing.JLabel Rechercher;
    private javax.swing.JLabel Suprrimer_Client;
    private javax.swing.JPanel Vente_Fenetre;
    private javax.swing.JLabel fermer;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel suprimer_events;
    // End of variables declaration//GEN-END:variables
}
