/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/**
 *
 * @author gamer
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public void Run() {
        initComponents();
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        getRootPane().setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(208, 208, 208)));
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nom_User = new javax.swing.JTextField();
        Pass_User = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Pass_Oublier = new javax.swing.JLabel();
        annuler = new javax.swing.JLabel();
        Connecter = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fermer = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 70));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nom_User.setBackground(new java.awt.Color(236, 240, 241));
        Nom_User.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nom_User.setForeground(new java.awt.Color(51, 51, 51));
        Nom_User.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        Nom_User.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Nom_UserKeyPressed(evt);
            }
        });
        jPanel1.add(Nom_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 270, 30));

        Pass_User.setBackground(new java.awt.Color(236, 240, 241));
        Pass_User.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pass_User.setForeground(new java.awt.Color(51, 51, 51));
        Pass_User.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        Pass_User.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Pass_UserKeyPressed(evt);
            }
        });
        jPanel1.add(Pass_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 270, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(193, 57, 43));
        jLabel1.setText("Nom d'utilisateur:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(193, 57, 43));
        jLabel2.setText("Mot de passe:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, 30));

        Pass_Oublier.setForeground(new java.awt.Color(51, 51, 51));
        Pass_Oublier.setText("Mot de passe oublié ?");
        Pass_Oublier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pass_OublierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pass_OublierMouseExited(evt);
            }
        });
        jPanel1.add(Pass_Oublier, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        annuler.setBackground(new java.awt.Color(255, 255, 255));
        annuler.setForeground(new java.awt.Color(51, 51, 51));
        annuler.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        annuler.setText("Annuler");
        annuler.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        annuler.setOpaque(true);
        annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annulerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                annulerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                annulerMouseExited(evt);
            }
        });
        jPanel1.add(annuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 350, 100, 30));

        Connecter.setBackground(new java.awt.Color(232, 76, 61));
        Connecter.setForeground(new java.awt.Color(255, 255, 255));
        Connecter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Connecter.setText("Se connecter");
        Connecter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(193, 57, 43)));
        Connecter.setOpaque(true);
        Connecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConnecterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConnecterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConnecterMouseExited(evt);
            }
        });
        Connecter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ConnecterKeyPressed(evt);
            }
        });
        jPanel1.add(Connecter, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 300, 100, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/member.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 60, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 460, 417));

        jPanel2.setBackground(new java.awt.Color(232, 76, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        fermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fermerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fermerMouseExited(evt);
            }
        });
        jPanel2.add(fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 50, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Se Connecté");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 190, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseClicked
        this.dispose();
    }//GEN-LAST:event_fermerMouseClicked

    private void fermerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseEntered
        fermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close_hover.png")));
    }//GEN-LAST:event_fermerMouseEntered

    private void fermerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseExited
        fermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png")));
    }//GEN-LAST:event_fermerMouseExited

    private void annulerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annulerMouseEntered
       annuler.setForeground(new java.awt.Color(193, 57, 43));
       annuler.setBackground(new java.awt.Color(236, 240, 241));
    }//GEN-LAST:event_annulerMouseEntered

    private void annulerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annulerMouseExited
       annuler.setForeground(new java.awt.Color(51, 51, 51));
       annuler.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_annulerMouseExited

    private void annulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annulerMouseClicked
       this.dispose();
    }//GEN-LAST:event_annulerMouseClicked

    private void ConnecterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnecterMouseEntered
        Connecter.setBackground(new java.awt.Color(255, 255, 255));
        Connecter.setForeground(new java.awt.Color(232, 76, 61));
    }//GEN-LAST:event_ConnecterMouseEntered

    private void ConnecterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnecterMouseExited
        Connecter.setBackground(new java.awt.Color(232, 76, 61));
        Connecter.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_ConnecterMouseExited

    private void Pass_OublierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pass_OublierMouseEntered
        Pass_Oublier.setForeground(new java.awt.Color(162, 162, 162));
    }//GEN-LAST:event_Pass_OublierMouseEntered

    private void Pass_OublierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pass_OublierMouseExited
        Pass_Oublier.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_Pass_OublierMouseExited

    private void ConnecterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnecterMouseClicked
       if("login".equals(Nom_User.getText()) && "123456".equals(Pass_User.getText())){
           home Home = new home();
           this.dispose();
           Home.Run();
       }
    }//GEN-LAST:event_ConnecterMouseClicked

    private void ConnecterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConnecterKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            if("login".equals(Nom_User.getText()) && "123456".equals(Pass_User.getText())){
                home Home = new home();
                this.dispose();
                Home.Run();
            }
        }
    }//GEN-LAST:event_ConnecterKeyPressed

    private void Nom_UserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nom_UserKeyPressed
        ConnecterKeyPressed(evt);
    }//GEN-LAST:event_Nom_UserKeyPressed

    private void Pass_UserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pass_UserKeyPressed
        ConnecterKeyPressed(evt);
    }//GEN-LAST:event_Pass_UserKeyPressed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Connecter;
    private javax.swing.JTextField Nom_User;
    private javax.swing.JLabel Pass_Oublier;
    private javax.swing.JPasswordField Pass_User;
    private javax.swing.JLabel annuler;
    private javax.swing.JLabel fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
